17 search results page
owal7428/CSCI-3308-Group-5-Project pull request #53
Opened 2022-11-17 00:11 UTC by owal7428

Implemented flights API and basic search page to see flights.

TODO:
- Add more search options to the search page
- Make the search page look nicer
- Integrate with calendar and weather API

NOTE:
If you are testing this page, please use POST as little as often as we only get another 90 requests for this month for the API.

Closes #17

2022-11-17 01:13 UTC, StudentKyle commented
Really hope that the 90 requests per month issue doesn't hurt us later, but I'll trust your judgement here.

2022-11-17 01:18 UTC, StudentKyle approved these changes
Looking at how you structured it, I expect it will be very easily added into the complete search bar I made, so this looks great.

However, I can't test the code without the API key, so you should wait for more reviews before merging.

2022-11-17 01:21 UTC, StudentKyle commented on All project code/index.js
> +            "arr_icao": req.body.city,
Even better that this seems to be the only user input we need to take. That data will come from the search bar once the city coordinate API is complete.

2022-11-17 01:23 UTC, StudentKyle requested changes

2022-11-17 01:23 UTC, StudentKyle commented on All project code/views/partials/menu.ejs
> +          <a class="nav-link" href = "/flights">Flights</a>
I think Profile has a different purpose, like displaying data on the user from the database (like, which destinatioins the user added to their account)? Maybe instead you should make an additional navbar item.

2022-11-17 20:32 UTC, StudentKyle commented
This PR should be renamed to be more specific: This doesn't create the results page, only some results for the flight API, as well as implementing that request as a whole. Instead of closing #17, which represents a fully completed search results page with all our data and user features, you should probably replace that with #6, which actually isn't complete until this PR is merged.

2022-11-17 20:33 UTC, StudentKyle commented
We don't want to have a hanging branch that stays unmerged until the full feature is done like you proposed in #6, because other PRs have made progress towards this other than this branch. Let's only make a PR for #17 once that is actually complete.

2022-11-17 20:41 UTC, StudentKyle requested changes
See above comments. While you can't easily rename the branch 17-search-results page, you can rename this pull request to something like "Implements Flight API" and add "Closes #6" instead of "Closes #17" to the PR description.
Just doing this so the PR is able to get merged and to be used in the actual development of the full search results page instead of a stale PR.

2022-11-18 21:31 UTC, owal7428 commented on All project code/views/partials/menu.ejs
> +          <a class="nav-link" href = "/flights">Flights</a>
I just moved profile, didn't delete it.

2022-11-18 21:32 UTC, StudentKyle approved these changes
Looks good. Next step is to integrate it into search bar in function searchQuery()

2022-11-18 21:32 UTC, merged